<?php
/**
 * Created by PhpStorm.
 * User: r8r
 * Date: 10/03/2018
 * Time: 10:20
 */

namespace SlackLight;

class Channel extends Entity {
    private $channelId;
    private $name;
    private $description;
    private $marked;

    public function __construct(int $channelId, string $channelName, string $channelDescription, int $channelMarked)  {
        parent::__construct($channelId);
        $this->name = $channelName;
        $this->description = $channelDescription;
        $this->marked = ($channelMarked == 0);


    }

    /*public function getChannelId() : int {
        return $this->channelId;
    }*/

    public function getChannelId() : int
    {
        return parent::getId(); // TODO: Change the autogenerated stub
    }

    public function getName() : string {
        return $this->name;
    }

    public function getDescription() :  string {
        return $this->description;
    }

    public function getMarked() :  bool {
        return $this->marked;
    }

    public function setMarked(bool $b) {
        $this->marked = $b;
    }
}