<?php
/**
 * Created by PhpStorm.
 * User: clk
 * Date: 27.05.18
 * Time: 09:46
 */

namespace SlackLight;


class Message extends Entity {
    private $authorId;
    private $channelId;
    private $text;
    private $timestamp;
    private $edited;
    private $deleted;
    private $marked;

    public function __construct(int $id, int $authorId, int $channelId, string $text,
                                string $creationDate, int $edited, int $deleted, int $marked) {
        parent::__construct($id);
        $this->authorId = $authorId;
        $this->channelId = $channelId;
        $this->text = $text;
        $this->timestamp = $creationDate;
        $this->edited = $edited != 0;
        $this->deleted = $deleted != 0;
        $this->marked = $marked != 0;
    }

    public function getId() : int
    {
        return parent::getId(); // TODO: Change the autogenerated stub
    }

    public function getAuthorId()
    {
        return $this->authorId;
    }

    public function getChannelId()
    {
        return $this->channelId;
    }

    public function getText()
    {
        return $this->text;
    }

    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function isEdited()
    {
        return $this->edited;
    }

    public function isDeleted()
    {
        return $this->deleted;
    }


    public function isMarked()
    {
        return $this->marked;
    }

}